# Generated by Django 3.2.6 on 2021-08-08 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=254, verbose_name='First Name')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=254, verbose_name='Message')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
