# Generated by Django 3.2.6 on 2021-08-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='general',
            name='person',
            field=models.CharField(blank=True, max_length=254, verbose_name='Person'),
        ),
    ]
