# Generated by Django 3.2.6 on 2021-08-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210808_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='general',
            name='last_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='First Name'),
        ),
    ]
