# Generated by Django 3.2.6 on 2021-08-08 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210808_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=254, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=254, verbose_name='First Name')),
                ('person', models.CharField(blank=True, max_length=254, verbose_name='Person')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=254, verbose_name='Message')),
                ('isTechnical', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='General',
        ),
    ]
