# Generated by Django 3.2.6 on 2021-08-09 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='email',
        ),
        migrations.AddField(
            model_name='announcement',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=254, verbose_name='Message'),
            preserve_default=False,
        ),
    ]
