# Generated by Django 3.2.6 on 2021-08-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210808_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcementID',
            field=models.IntegerField(default=6564736),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(max_length=10000, verbose_name='Message'),
        ),
    ]
