# Generated by Django 3.2.6 on 2021-08-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210808_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='announcementID',
        ),
    ]
