# Generated by Django 3.2.6 on 2021-08-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210809_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='datesID',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
