# Generated by Django 3.2.6 on 2021-08-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_dates_datesid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='wasSeen',
            field=models.BooleanField(default=False),
        ),
    ]
