# Generated by Django 3.1.7 on 2021-09-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210917_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='Year')),
                ('position', models.CharField(max_length=254)),
                ('year', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='inductees',
            name='inductees',
            field=models.TextField(max_length=2000, verbose_name='Message'),
        ),
    ]
