# Generated by Django 3.1.7 on 2021-09-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210917_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductees',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
