# Generated by Django 3.1.7 on 2021-10-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_inductees_hide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='dates',
            options={'verbose_name': 'Date', 'verbose_name_plural': 'Dates'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterModelOptions(
            name='inductees',
            options={'verbose_name': 'List of Inductees', 'verbose_name_plural': 'Inductees'},
        ),
        migrations.AlterModelOptions(
            name='officers',
            options={'verbose_name': 'List of Officers', 'verbose_name_plural': 'Officers'},
        ),
        migrations.RemoveField(
            model_name='officers',
            name='year',
        ),
        migrations.AlterField(
            model_name='officers',
            name='name',
            field=models.CharField(blank=True, max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='officers',
            name='position',
            field=models.TextField(max_length=254, verbose_name='Position'),
        ),
    ]
