# Generated by Django 3.1.7 on 2021-10-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20211016_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='officers',
            name='isBig',
            field=models.BooleanField(default=False),
        ),
    ]
